revert: go back to using pg instead of postgres.js
currently getting the following:
PostgresError: unrecognized configuration parameter "schema"

Signed-off-by: Seren_Modz 21 <seren@kings-world.net>